### ISSUE TITLE
exportpdftoimages : error ServiceApiError

### ISSUE THREAD

**Issue by vivo95** [adobe/pdfservices-node-sdk-samples#42]
Hello, I'm new and I'm trying to use @adobe/pdfservices-node-sdk to convert pdf to jpeg.
some time ago, I managed to convert, but since yesterday impossible and I have an error "Exception encountered while executing operation ServiceApiError"

`2023-05-15T11:01:53.681:[INFO]: All validations successfully done. Beginning Export PDF to Images Operation execution
Exception encountered while executing operation ServiceApiError
    at rejectWithServiceApiError (..\node_modules\@adobe\pdfservices-node-sdk\src\internal\http\http-client.js:31:17)
    at handleJsonResponse (..\node_modules\@adobe\pdfservices-node-sdk\src\internal\http\http-client.js:55:3)
    at handleErrorResponse (..\node_modules\@adobe\pdfservices-node-sdk\src\internal\http\http-client.js:117:2)
    at onEnd (..\node_modules\@adobe\pdfservices-node-sdk\src\internal\http\http-client.js:176:3)
    at IncomingMessage.<anonymous> (..\node_modules\@adobe\pdfservices-node-sdk\src\internal\http\http-client.js:216:5)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  requestTrackingId: undefined,
  statusCode: 400,
  errorCode: 'UNKNOWN'`

I applied the same code present in "src/exportpdftoimages/export-pdf-to-jpeg.js", copy the credential.json file and my private key.

Can you help me?

**Comment by tulaseerao** [comment]
We are also having the same issue with PDF extraction.  Please help us resolve this issue

**Comment by tulaseerao** [comment]
It w

> We are also having the same issue with PDF extraction. Please help us resolve this issue

It worked after upgrading to 3.3.0 👍

**Comment by varkumaradobe** [comment]
Hi @vivo95, above-mentioned issue is resolved, hence closing it.
